### ISSUE TITLE
Swagger hosted via github page gives ERR_CERT_COMMON_NAME_INVALID 

### ISSUE THREAD

**Issue by vinay32724** [peter-evans/swagger-github-pages#12]
1. Host any swagger via github pages
2. Swagger is hosted @ https://peter-evans.github.io/swagger-github-pages/ 
3. Click on Try it out option
4. It doesn't work and responds with FAILED to fetch
5. Open console and observe ERR_CERT_COMMON_NAME_INVALID  

This may be because the swagger is hosted on one domain and the API that's being testing on another domain. How to resolve this ?

**Comment by peter-evans** [comment]
@vinay32724 Thank you for letting me know that the example wasn't working. I fixed it by updating the swagger.yaml to make sure it supports the `https` scheme.

```diff
  schemes:
+ - "https"
  - "http"
```

If you are having trouble with your own API, you need to make sure it supports CORS. See documentation [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/cors.md) for more information.
