### ISSUE TITLE
Copy button is not indicating the text was copied or not

### ISSUE THREAD

**Issue by swethamekaa** [peter-evans/swagger-github-pages#124]
Hello Team,

After clicking on the copy button its not showing the text like "copied", i wanted to customized this one , can you help us.. 
Swagger-ui:@^4.15.5,
react:@^17.0.2
![swagger](https://github.com/peter-evans/swagger-github-pages/assets/92969511/cd41b6bc-92b0-44e4-aef7-0f587f38ce91)

**Comment by peter-evans** [comment]
Hi @swethamekaa 

I'm afraid I can't help you with this because I don't maintain the swagger-ui component. You could try asking about that feature here: https://github.com/swagger-api/swagger-ui

**Comment by swethamekaa** [comment]
> After clicking on the copy button its not showing the text like "copied", i wanted to customized this one , can you help us..
> Swagger-ui:@^4.15.5,
> react:@^17.0.2
Thank you for your response... sure I'll connect with them...
