### ISSUE TITLE
Changing the logo

### ISSUE THREAD

**Issue by eddySlip** [peter-evans/swagger-github-pages#127]
Really enjoying using this project, massive help. 

I was wondering if you could help in how to change the default logo on the page. 

![Screenshot 2023-07-21 at 11 59 51](https://github.com/peter-evans/swagger-github-pages/assets/96153020/f0734c96-59e0-47ab-9943-20206d37bcba)

**Comment by peter-evans** [comment]
Hi @eddySlip 

Glad you've found this project useful.

I'm afraid I don't know how to change the logo. You could try asking the Swagger folks [here](https://github.com/swagger-api/swagger-ui).
