### ISSUE TITLE
Remote swagger file?

### ISSUE THREAD

**Issue by romrell4** [peter-evans/swagger-github-pages#129]
Does this repo support pulling an openApi file from a hosted URL, rather than a local file? If not, could it?

In case it helps, my use case is that I have an existing private repo with an auto-generated openApi.yml file. I'd LOVE to add a swagger ui github page to it, but making the repo public isn't an option. I'm working around it right now via scripting by copying over the file contents into the public swagger-ui repo, but it would be much easier if I were able to host the API spec outside the repo and point to it :)

**Comment by peter-evans** [comment]
Hi @romrell4 

I don't know the answer to your question, so I suggest just trying it. If you need further help try reaching out to the maintainers of the [swagger-ui](https://github.com/swagger-api/swagger-ui) component.
