### ISSUE TITLE
Load external in api specs

### ISSUE THREAD

**Issue by tunglt1810** [peter-evans/swagger-github-pages#132]
Hi,
Your repo is so great. I'm following your guide lines to setup my repo. And i found an issue when using external refs in api spec yaml file. It's look like the swagger-ui cannot load the external files, maybe it because of hosting deployment.
I defined external refs in examples of request
 ```
             examples:
                response:
                  externalValue: ./token_balances/_TokenBalancesResponse.json
       
```
Can you give some recommendation for finding solution for this issue

<img width="1202" alt="image" src="https://github.com/peter-evans/swagger-github-pages/assets/19906349/61f2cd5b-b845-48c2-a0a7-2e6d1f4078ad">

**Comment by tunglt1810** [comment]
I decode that text and it is a 404 page :D. Maybe the ui cannot load file from private repo
<img width="979" alt="image" src="https://github.com/peter-evans/swagger-github-pages/assets/19906349/0b916ae5-61f3-40b2-a68d-79302c2516c3">

**Comment by peter-evans** [comment]
Hi @tunglt1810 

Sorry I don't know anything about how to do this. It might help to ask the [swagger-ui](https://github.com/swagger-api/swagger-ui) folks.
