### ISSUE TITLE
Swagger config file

### ISSUE THREAD

**Issue by HermanPlay** [peter-evans/swagger-github-pages#134]
Is it possible to add swagger config file (swagger-config.json)? 

I have tried adding `swagger-config.json` to the `root`, as well as the `dist/` but SwaggerUIBandle doesn't find it. Or atleast it doesn't change anything.

I need this to specify `operationsSorter` parameter of the SwaggerUI

**Comment by peter-evans** [comment]
Hi @HermanPlay 

I'm sorry I don't know the answer to this. You could try asking at [swagger-ui](https://github.com/swagger-api/swagger-ui), who are the folks who maintain the component.
