### ISSUE TITLE
Is this work with springdoc-openapi

### ISSUE THREAD

**Issue by mikebgrep** [peter-evans/swagger-github-pages#150]
Hi, is this Swagger template works with springdoc-openapi variation of Swagger?

**Comment by mikebgrep** [comment]
I am closing the issue. I found the answer here
https://stackoverflow.com/a/70059281/19219457

**Comment by peter-evans** [comment]
Hi @mikebgrep 

I don't know anything about that project, I'm afraid, so I don't know whether it would work or not. If you find that it does work, please let me know!
