### ISSUE TITLE
License seems to be missing

### ISSUE THREAD

**Issue by g-io** [peter-evans/swagger-github-pages#160]
Hi @peter-evans ,

thank you for this nice template!

Would you mind adding a LICENSE file?
That would help adoption in certain cases.
In case there is a license mentioned and I've not seen it, I apologize and am happy to take any hint as where to find it.

Thank you,
Ole

**Comment by peter-evans** [comment]
Hi @g-io 

I've add a `LICENSE` file. Hope that helps.
