### ISSUE TITLE
Swagger UI GitHub Action

### ISSUE THREAD

**Issue by Legion2** [peter-evans/swagger-github-pages#30]
I created a [Swagger UI GitHub Action](https://github.com/marketplace/actions/swagger-ui-action) which can be used to automatically generate the Swagger UI static html files based on a spec file and a swagger-config file. The generated Swagger UI is customizable via GitHub Actions inputs and the output can be deployed to GitHub Pages. The Action can be used in the same repository as the REST API service itself and be automatically updated with generated spec files with every push to the git repository.

I used this repository as inspiration to build the Action and how to download and generate the files of the swagger ui. I just wanted to add this here as an alternative to setting up this template repository and customizing swagger ui by hand.

**Comment by peter-evans** [comment]
Hi @Legion2 

Great! Nice job on the action.

For this repository I think I'm going to keep using my workflow because it serves as a good example of writing this kind of workflow in GitHub Actions. But privately I'm going to check this out and maybe use it.

Thanks for letting me know!
